spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5433/store_db
    username: isswmq
    password: moonrock19
    driver-class-name: org.postgresql.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true
logging:
  level:
    root: info
  file:
    name: store.log
    path: /